package com.elliott;

public enum TokenType {
    //Single Character Tokens

    O_PAREN, C_PAREN, O_SQUARE, C_SQUARE, BANG, APOSTROPHE, 

    //LITERAL

    IDENTIFIER, WORD, NUM, MORAL, GOOD, EVIL, GHOUL,

    //Keywords

    HOLLER, HITHER, SQUIRE, GIVE, COMBINE, SMASH, WITCHCRAFT, CHOP, SEER, VOODOO, HOLD, DO, WITH, AND, RETRIEVE, DIVINE,
    VILLAIN, RIVER, TROLLS, WORK, FOR, FOOD, FOODLEFT, FEED, MOUNTAIN, TROLL, MISCHIEVOUS, PLAY, SWITCH, DESPAIR, HOLY, REALISTIC,
    PRETTYGOOD, BETTER, EQUAL, BETTEREQUAL, BUILD, TAVERN, ROOMS, GUEST, ROOM,

    //COMMENT

    O_BRACKET, C_BRACKET,

    EOF
}
