package com.elliott;

public enum TokenType {
    //Single Character Tokens

    O_PAREN, C_PAREN, O_SQUARE, C_SQUARE, BANG, COMMA,

    //LITERAL

    IDENTIFIER, WORD, NUM, NUM_WITH_CALC, MORAL, GOOD, EVIL, GHOUL,

    //Keywords

    HOLLER, HITHER, SQUIRE, GIVE, COMBINE, SMASH, WITCHCRAFT, CHOP, SEER, VOODOO, HOLD, DO, WITH, AND, RETRIEVE, DIVINE,
    VILLAIN, RIVER, TROLLS, WORK, FOR, FOOD, FOOD_LEFT, FEED, MOUNTAIN, TROLL, MISCHIEVOUS, PLAY, SWITCH, DESPAIR, HOLY, REALISTIC,
    PRETTY_GOOD, BETTER, EQUAL, BETTER_EQUAL, BUILD, TAVERN, ROOMS, GUEST, ROOM, ROOM_NUMBER,

    //Parser Types

    PROGRAM, STATEMENT_LIST, STATEMENT, RIVER_TROLLS, GLUE,
    TAVERN_CALL, GROUP, PRIMARY_LIST, FUNCTION_CALL, INITIALIZATION, PARAMETER, DECLARATION,
    ASSIGNMENT, TAVERN_ASSIGNMENT, PARAMETER_LIST,

    //COMMENT

    O_BRACKET, C_BRACKET,

    EOF
}
